//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaTuerca
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedors
    {
        public Proveedors()
        {
            this.Repuestoes = new HashSet<Repuestoes>();
        }
    
        public int Id { get; set; }
        public string RazonSocial { get; set; }
        public string Ruc { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
    
        public virtual ICollection<Repuestoes> Repuestoes { get; set; }
    }
}
